url: https://alexhidalgo.github.io
baseurl:

# Site settings
title: Alex Hidalgo
email: aj1hidalgo@gmail.com
description: "Alex Hidalgo is a Front-End Engineer student at the IronYard coding school in Austin, Texas. Previously a principal consultant for BlackLite Labs, a web and mobile development shop in Dallas, he has not pursued his passion for programming."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FFA500
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Alex Hidalgo
  pic: 1
  position: Front-End Engineer
  social:
    - title: twitter
      url: https://twitter.com/thealexhidalgo
    - title: linkedin
      url: https://www.linkedin.com/profile/view?id=47399960&trk=nav_responsive_tab_profile_pic
    - title: github
      url: https://github.com/alexhidalgo

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
    - title: twitter
      url: https://twitter.com/thealexhidalgo
    - title: linkedin
      url: https://www.linkedin.com/profile/view?id=47399960&trk=nav_responsive_tab_profile_pic
    - title: github
      url: https://github.com/alexhidalgo
# Postal address (add as many lines as necessary)
address:
  - line: Austin, Texas

# Blog
paginate_path: "/blog/page:num/"
paginate: 5

# Build settings
markdown: kramdown
permalink: pretty
