url: https://alexhidalgo.github.io
baseurl: 

# Site settings
title: Alex Hidalgo
email: aj1hidalgo@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Alex Hidalgo
  pic: 1
  position: Front-End Engineer
  social:
    - title: twitter
      url: https://twitter.com/dallashidalgo
    - title: linkedin
      url: https://www.linkedin.com/profile/view?id=47399960&trk=nav_responsive_tab_profile_pic
    - title: github
      url: https://github.com/alexhidalgo

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
    - title: twitter
      url: https://twitter.com/dallashidalgo
    - title: linkedin
      url: https://www.linkedin.com/profile/view?id=47399960&trk=nav_responsive_tab_profile_pic
    - title: github
      url: https://github.com/alexhidalgo
# Postal address (add as many lines as necessary)
address:
  - line: Austin, Texas

# Build settings
markdown: kramdown
permalink: pretty
